services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
      - key: SERPAPI_KEY
        value: YOUR_SERPAPI_KEY
      - key: SUPABASE_URL
        value: YOUR_SUPABASE_URL
      - key: SUPABASE_KEY
        value: YOUR_SUPABASE_KEY
      - key: FASTAPI_SECRET_KEY
        value: YOUR_FASTAPI_SECRET_KEY

  - type: web
    name: streamlit-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
      - key: SERPAPI_KEY
        value: YOUR_SERPAPI_KEY
      - key: SUPABASE_URL
        value: YOUR_SUPABASE_URL
      - key: SUPABASE_KEY
        value: YOUR_SUPABASE_KEY
      - key: FASTAPI_SECRET_KEY
        value: YOUR_FASTAPI_SECRET_KEY
