name: Cleanup PM All Table

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3am UTC
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install supabase

      - name: Run cleanup script
        run: python backend/utils/remove_past_future_pms.py